apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-master
spec:
  replicas: {{ .Values.postgresql.cluster.master.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      role: master
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        role: master
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432

