apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  POSTGRES_DB: {{ .Values.postgresql.config.database }}
  POSTGRES_USER: {{ .Values.postgresql.config.username }}
  POSTGRES_PORT: {{ .Values.postgresql.config.port | quote }}

