apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  clusterIP: None

