apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password.generate | ternary (randAlphaNum 12) .Values.postgresql.password | b64enc }}

